require_relative "phron_bot/letter_page"
require_relative "phron_bot/dictionary"
require_relative "phron_bot/scraper"
require_relative "phron_bot/randomnumber"
require_relative "phron_bot/pickword"
require_relative "phron_bot/tweet"
